elastic-master:
  image: quay.io/7insyde/elastic
  container_name: elastic-master
  ports:
      - "9300"
  environment:
      - ELASTIC_NODE_MASTER=true
      - ELASTIC_NODE_DATA=false
      - ELASTIC_HTTP_ENABLE=false
      - ELASTIC_MULTICAST=true
  volumes:
      - /data/elastic:/data/elastic
elastic-client:
  image: quay.io/7insyde/elastic
  container_name: elastic-client
  ports:
      - "9200:9200"
      - "9300"
  environment:
      - ELASTIC_NODE_MASTER=false
      - ELASTIC_NODE_DATA=false
      - ELASTIC_HTTP_ENABLE=true
      - ELASTIC_MULTICAST=true
  volumes:
      - /data/elastic:/data/elastic
elastic-data:
  image: quay.io/7insyde/elastic
  container_name: elastic-data
  ports:
      - "9300"
  environment:
      - ELASTIC_NODE_MASTER=false
      - ELASTIC_NODE_DATA=true
      - ELASTIC_HTTP_ENABLE=false
      - ELASTIC_MULTICAST=true
  volumes:
      - /data/elastic:/data/elastic
kibana:
  image: quay.io/7insyde/kibana
  container_name: kibana
  ports:
      - "5601:5601"
  links:
      - elastic-client
logstash:
  image: quay.io/7insyde/logstash
  container_name: logstash
  ports:
      - "5044"
      - "12201:12201/udp"
  links:
      - elastic-client
topbeat:
  image: quay.io/7insyde/topbeat
  container_name: topbeat
  privileged: true
  links:
      - logstash
fluentd:
  image: quay.io/7insyde/fluentd
  container_name: fluentd
  ports:
      - "24224:24224"
  links:
      - elastic-client
