cluster:
  name: ${ELASTIC_NAME}

node:
  master: ${ELASTIC_NODE_MASTER}
  data: ${ELASTIC_NODE_DATA}

path:
  data: /data/${ELASTIC_NAME}/data
  logs: /data/${ELASTIC_NAME}/logs
  plugins: ${ELASTIC_PATH}/plugins
  work: /data/${ELASTIC_NAME}/work

bootstrap.mlockall: true

network.host: 0.0.0.0
http.enabled: ${ELASTIC_HTTP_ENABLE}

discovery.zen.ping.multicast.enabled: ${ELASTIC_MULTICAST}
discovery.zen.ping.multicast.address: _eth0:ipv4_

index.analysis.analyzer.default.type: keyword
